### ISSUE TITLE
several unit tests fail exclusively on windows

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/thermotools#27]
On appveyor, the following unit tests fail for all settings:

```
test_bar.test_bar ... FAIL
test_callback.test_dtram_stop ... FAIL
test_dtram.test_lognu_all_factors_unity ... FAIL
test_dtram.test_lognu_K_range ... FAIL
test_dtram.test_fi_all_factors_unity ... FAIL
test_dtram.test_pij_all_factors_unity ... FAIL
test_mbar.test_mbar_fk_with_ascending_bias ... FAIL
test_util.test_logsumexp_zeros ... FAIL
test_util.test_logsumexp_converged_geometric_series ... FAIL
test_util.test_logsumexp_pair ... FAIL
test_wham.test_wham_fk_with_zeros ... FAIL
test_wham.test_wham_fi_with_ascending_K ... FAIL
```

Here are details on how the tests failed:

```
======================================================================
FAIL: test_bar.test_bar
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_bar.py", line 44, in test_bar
    assert_allclose(bar.df(dbIJ, dbJI, np.zeros(dbJI.shape[0])), delta_f_gaussian(), atol=1.0E-1)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 100.0%)
 x: array(-7.636789781749844)
 y: array(1.609437912434101)
```

```
======================================================================
FAIL: test_callback.test_dtram_stop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_callback.py", line 62, in test_dtram_stop
    assert_allclose(conf_energies, np.log(M), atol=1.0E-15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-15

(mismatch 100.0%)
 x: array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
 y: array(2.302585092994046)
```

```
======================================================================
FAIL: test_dtram.test_lognu_all_factors_unity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_dtram.py", line 53, in test_lognu_all_factors_unity
    assert_allclose(new_log_lagrangian_mult, ref_log_lagrangian_mult, atol=1.0E-16)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-16

(mismatch 100.0%)
 x: array([[ 5.988961,  5.988961,  5.988961, ...,  5.988961,  5.988961,
         5.988961],
       [ 5.988961,  5.988961,  5.988961, ...,  5.988961,  5.988961,...
 y: array([[ 5.298317,  5.298317,  5.298317, ...,  5.298317,  5.298317,
         5.298317],
       [ 5.298317,  5.298317,  5.298317, ...,  5.298317,  5.298317,...
```

```
======================================================================
FAIL: test_dtram.test_lognu_K_range
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_dtram.py", line 70, in test_lognu_K_range
    assert_allclose(new_log_lagrangian_mult, ref_log_lagrangian_mult, atol=1.0E-16)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-16

(mismatch 1.0%)
 x: array([[ 5.988961,  5.988961,  5.988961, ...,  5.988961,  5.988961,
         5.988961],
       [ 5.298317,  5.298317,  5.298317, ...,  5.298317,  5.298317,...
 y: array([[ 5.298317,  5.298317,  5.298317, ...,  5.298317,  5.298317,
         5.298317],
       [ 5.298317,  5.298317,  5.298317, ...,  5.298317,  5.298317,...
```

```
======================================================================
FAIL: test_dtram.test_fi_all_factors_unity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_dtram.py", line 101, in test_fi_all_factors_unity
    assert_allclose(new_conf_energies, 0.0, atol=1.0E-16)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-16

(mismatch 100.0%)
 x: array([ 0.690644,  0.690644,  0.690644,  0.690644,  0.690644,  0.690644,
        0.690644,  0.690644,  0.690644,  0.690644,  0.690644,  0.690644,
        0.690644,  0.690644,  0.690644,  0.690644,  0.690644,  0.690644,...
 y: array(0.0)
```

```
======================================================================
FAIL: test_dtram.test_pij_all_factors_unity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_dtram.py", line 132, in test_pij_all_factors_unity
    assert_allclose(p_K_ij[K, :, :], ref_p_ij, atol=1.0E-16)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-16

(mismatch 100.0%)
 x: array([[ 0.002506,  0.005013,  0.005013, ...,  0.005013,  0.005013,
         0.005013],
       [ 0.005013,  0.002506,  0.005013, ...,  0.005013,  0.005013,...
 y: array([[ 0.005,  0.005,  0.005, ...,  0.005,  0.005,  0.005],
       [ 0.005,  0.005,  0.005, ...,  0.005,  0.005,  0.005],
       [ 0.005,  0.005,  0.005, ...,  0.005,  0.005,  0.005],...
```

```
======================================================================
FAIL: test_mbar.test_mbar_fk_with_ascending_bias
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_mbar.py", line 46, in test_mbar_fk_with_ascending_bias
    assert_allclose(new_therm_energies, ref, atol=1.0E-15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-15

(mismatch 80.0%)
 x: array([ 0.      , -1.302585, -0.302585,  0.697415,  1.697415])
 y: array([ 0.,  1.,  2.,  3.,  4.])
```

```
======================================================================
FAIL: test_util.test_logsumexp_zeros
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_util.py", line 62, in test_logsumexp_zeros
    assert_almost_equal(util.logsumexp(data, inplace=False), np.log(N), decimal=15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 510, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 15 decimals
 ACTUAL: 0.0
 DESIRED: 9.2103403719761836
```

```
======================================================================
FAIL: test_util.test_logsumexp_converged_geometric_series
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_util.py", line 69, in test_logsumexp_converged_geometric_series
    0.45867514538708193, decimal=15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 510, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 15 decimals
 ACTUAL: 0.0
 DESIRED: 0.45867514538708193
```

```
======================================================================
FAIL: test_util.test_logsumexp_pair
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_util.py", line 102, in test_logsumexp_pair
    assert_almost_equal(util.logsumexp_pair(0.0, 0.0), np.log(2.0), decimal=15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 510, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 15 decimals
 ACTUAL: 0.0
 DESIRED: 0.69314718055994529
```

```
======================================================================
FAIL: test_wham.test_wham_fk_with_zeros
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_wham.py", line 31, in test_wham_fk_with_zeros
    assert_allclose(therm_energies, ref, atol=1.0E-15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-15

(mismatch 100.0%)
 x: array([-0., -0., -0., -0., -0.])
 y: array(-2.302585092994046)
```

```
======================================================================
FAIL: test_wham.test_wham_fi_with_ascending_K
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3\conda-bld\work\test\test_wham.py", line 74, in test_wham_fi_with_ascending_K
    assert_allclose(conf_energies, ref, atol=1.0E-15)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-15

(mismatch 10.0%)
 x: array([-1.609438, -0.693147, -1.098612, -1.386294, -1.609438, -1.791759,
       -1.94591 , -2.079442, -2.197225, -2.302585])
 y: array([-0.      , -0.693147, -1.098612, -1.386294, -1.609438, -1.791759,
       -1.94591 , -2.079442, -2.197225, -2.302585])
```

**Comment by cwehmeyer** [comment]
Done
